name: Arduino CI for Juicer3
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        
      - name: Update Arduino CLI Core Index
        run: arduino-cli core update-index
        
      - name: Install ESP32 Core 3.1.1
        run: arduino-cli core install esp32:esp32@3.1.1
        
      - name: Install Required Libraries
        run: |
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit ST7735 and ST7789 Library"
          arduino-cli lib install "Adafruit NeoPixel"
          arduino-cli lib install "ArduinoJson"
          # Libraries like SPI and Preferences are bundled in the core
          
      - name: Patch USB_PRODUCT Definition
        run: |
          FILE_PATH="$HOME/.arduino15/packages/esp32/hardware/esp32/3.1.1/variants/adafruit_feather_esp32s3_reversetft/pins_arduino.h"
          if [ -f "$FILE_PATH" ]; then
            sed -i 's/#define USB_PRODUCT .*/#define USB_PRODUCT "juicer3"/' "$FILE_PATH"
          else
            echo "Error: File not found at $FILE_PATH"
            exit 1
          fi

      - name: Compile Arduino Sketch
        run: arduino-cli compile --fqbn esp32:esp32:adafruit_feather_esp32s3_reversetft --build-path build ./juice_pump3

      # Upload as artifact (with specific version)
      - name: Upload Compiled Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: build/juice_pump3.ino.bin
          retention-days: 90
          
      # Create release when a tag is pushed
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/juice_pump3.ino.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




